//! wasm-bindgen bindings over `poid-core` for the Web Reader.
//!
//! This crate is a thin translation layer: every check is performed by
//! `poid-core`, compiled to `wasm32-unknown-unknown` — the Web Reader runs
//! **the same validation code as the desktop reader**, not a TypeScript
//! reimplementation (M05: "Do not reimplement it in TS").
//!
//! [`open_container`] is reader-grade validation: SPEC §2 structural checks,
//! integrity digests (SPEC §3.3) and the signature (SPEC §9.3). Every
//! rejection surfaces as a [`ContainerError`] carrying the stable diagnostic
//! code and the normative `POID-xxx` registry code, so the UI can show both
//! the code and a human explanation.
//!
//! The crate deliberately has no randomness source: `instance.id` (SPEC §6.3)
//! is generated by the caller with `crypto.randomUUID()` and passed in.

mod convert;

pub use convert::{classify_project, converted_manifest, inline_into_html};

use poid_core::{conformance_check, Limits, PoidError, SignatureStatus, Uuid};
use wasm_bindgen::prelude::*;

/// A container rejection, exposed to JavaScript as a thrown object.
///
/// `code` is the stable diagnostic slug (`poid-core`'s `PoidError::code`),
/// `registry` the normative conformance code from `spec/errors.md`, and
/// `message` the human-readable explanation.
#[derive(Debug)]
#[wasm_bindgen]
pub struct ContainerError {
    pub(crate) code: String,
    pub(crate) registry: Option<String>,
    pub(crate) message: String,
}

#[wasm_bindgen]
impl ContainerError {
    /// Stable diagnostic code, e.g. `native-code`.
    #[wasm_bindgen(getter)]
    pub fn code(&self) -> String {
        self.code.clone()
    }

    /// Normative registry code, e.g. `POID-020`; absent for errors that say
    /// nothing about the container itself.
    #[wasm_bindgen(getter)]
    pub fn registry(&self) -> Option<String> {
        self.registry.clone()
    }

    /// Human-readable explanation.
    #[wasm_bindgen(getter)]
    pub fn message(&self) -> String {
        self.message.clone()
    }
}

impl From<PoidError> for ContainerError {
    fn from(e: PoidError) -> Self {
        Self {
            code: e.code().to_owned(),
            registry: e.conformance_code().map(str::to_owned),
            message: e.to_string(),
        }
    }
}

/// A validated, opened container held in WASM memory.
///
/// Mutation is limited to what the Web Reader needs: assigning the instance
/// identity on first open (SPEC §6.3) and replacing the embedded state before
/// *Download updated file* (SPEC §6.2).
#[wasm_bindgen]
pub struct WebPoid {
    inner: poid_core::Poid,
    signature: SignatureStatus,
}

/// Opens and validates container bytes at reader grade: SPEC §2 structure,
/// §3.3 integrity, §9.3 signature. Rejections throw a [`ContainerError`].
#[wasm_bindgen(js_name = openContainer)]
pub fn open_container(bytes: &[u8]) -> Result<WebPoid, ContainerError> {
    let poid = conformance_check(bytes, &Limits::default())?;
    let signature = poid.signature_status()?;
    Ok(WebPoid {
        inner: poid,
        signature,
    })
}

#[wasm_bindgen]
impl WebPoid {
    /// The parsed, validated manifest as a JSON string. Unknown fields are
    /// preserved (SPEC §3), so this is faithful to the file.
    #[wasm_bindgen(js_name = manifestJson)]
    pub fn manifest_json(&self) -> Result<String, ContainerError> {
        let bytes = self
            .inner
            .manifest()
            .to_json_bytes()
            .map_err(PoidError::from)?;
        String::from_utf8(bytes).map_err(|e| ContainerError {
            code: "manifest-encoding".to_owned(),
            registry: None,
            message: format!("manifest is not valid UTF-8 after serialization: {e}"),
        })
    }

    /// Signature state for the consent screen: `"unsigned"` or `"valid"`.
    /// (An *invalid* signature never reaches this point — [`open_container`]
    /// rejects it with `POID-050`.)
    #[wasm_bindgen(js_name = signatureStatus)]
    pub fn signature_status(&self) -> String {
        match self.signature {
            SignatureStatus::Valid { .. } => "valid".to_owned(),
            _ => "unsigned".to_owned(),
        }
    }

    /// All container file paths (excluding the generated `mimetype` and
    /// `manifest.json`), sorted.
    #[wasm_bindgen(js_name = filePaths)]
    pub fn file_paths(&self) -> Vec<String> {
        self.inner.files().map(|(p, _)| p.to_owned()).collect()
    }

    /// Content of one file entry, or `undefined` if absent.
    pub fn file(&self, path: &str) -> Option<Vec<u8>> {
        self.inner.file(path).map(<[u8]>::to_vec)
    }

    /// Embedded application state (`data/store.json`), if present (SPEC §6.2).
    pub fn data(&self) -> Option<Vec<u8>> {
        self.inner.data().map(<[u8]>::to_vec)
    }

    /// Writes the instance identity assigned by the reader on first open
    /// (SPEC §6.3). `id` must be a UUID string, e.g. from `crypto.randomUUID()`.
    #[wasm_bindgen(js_name = setInstanceId)]
    pub fn set_instance_id(&mut self, id: &str) -> Result<(), ContainerError> {
        let uuid = Uuid::parse_str(id).map_err(|e| ContainerError {
            code: "invalid-argument".to_owned(),
            registry: None,
            message: format!("`{id}` is not a UUID: {e}"),
        })?;
        self.inner.set_instance_id(uuid);
        Ok(())
    }

    /// Replaces the embedded application state (SPEC §6.2), used before
    /// *Download updated file*.
    #[wasm_bindgen(js_name = setData)]
    pub fn set_data(&mut self, data: &[u8]) {
        self.inner.set_data(data);
    }

    /// Packs the container deterministically (SPEC §2.1) for download.
    /// Because the signature payload excludes `instance` and storage state
    /// (SPEC §9.3.2), a signed container stays validly signed after
    /// [`WebPoid::set_instance_id`] and [`WebPoid::set_data`].
    #[wasm_bindgen(js_name = toBytes)]
    pub fn to_bytes(&self) -> Result<Vec<u8>, ContainerError> {
        Ok(self.inner.to_bytes()?)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture_bytes(name: &str) -> Vec<u8> {
        poid_fixtures::conformance_fixtures()
            .expect("fixtures build")
            .into_iter()
            .find(|f| f.name == name)
            .expect("fixture exists")
            .bytes
    }

    #[test]
    fn opens_a_valid_container_and_exposes_the_manifest() {
        let poid = open_container(&fixture_bytes("embedded-data")).expect("opens");
        let manifest = poid.manifest_json().expect("serializes");
        assert!(manifest.contains("org.poid.conformance.embedded"));
        assert_eq!(poid.signature_status(), "unsigned");
        assert!(poid.file("app/index.html").is_some());
        assert!(poid.data().is_some());
    }

    #[test]
    fn rejects_native_code_with_the_registry_code() {
        let err = match open_container(&fixture_bytes("contains-exe")) {
            Err(e) => e,
            Ok(_) => panic!("a container with an .exe must not open"),
        };
        assert_eq!(err.code, "native-code");
        assert_eq!(err.registry.as_deref(), Some("POID-020"));
        assert!(!err.message.is_empty());
    }

    #[test]
    fn signed_fixture_reports_a_valid_signature() {
        let poid = open_container(&fixture_bytes("signed")).expect("opens");
        assert_eq!(poid.signature_status(), "valid");
    }

    #[test]
    fn instance_id_and_data_survive_a_repack_round_trip() {
        let mut poid = open_container(&fixture_bytes("minimal-html")).expect("opens");
        poid.set_instance_id("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
            .expect("valid uuid");
        poid.set_data(br#"{"note":"hello"}"#);
        let bytes = poid.to_bytes().expect("packs");
        let reopened = open_container(&bytes).expect("reopens");
        assert_eq!(
            reopened.data().as_deref(),
            Some(&br#"{"note":"hello"}"#[..])
        );
        let manifest = reopened.manifest_json().expect("serializes");
        assert!(manifest.contains("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"));
    }

    #[test]
    fn rejects_a_bad_instance_id_without_touching_the_container() {
        let mut poid = open_container(&fixture_bytes("minimal-html")).expect("opens");
        let err = match poid.set_instance_id("not-a-uuid") {
            Err(e) => e,
            Ok(()) => panic!("a malformed uuid must be rejected"),
        };
        assert_eq!(err.code, "invalid-argument");
        assert_eq!(err.registry, None);
    }
}
